// This C file was autogenerated from Coq
#include <stdbool.h>
#include <stdint.h>

void executeM64(RiscvState s, InstructionM64 inst) {
    switch (inst.kind) {
        case K_Mulw:
            t x = getRegister(rs1);
            t y = getRegister(rs2);
            setRegister(rd, s32(h0, mul(h0, x, y)));
            break;
        case K_Divw:
            t x = getRegister(rs1);
            t y = getRegister(rs2);
            t q = ((reg_eqb(h0, x, minSigned(h0)) && reg_eqb(h0, y, negate(h0, coq_ZToReg(h0, 0b1))))
                ? x
                : ((reg_eqb(h0, y, coq_ZToReg(h0, 0b0)))
                    ? negate(h0, coq_ZToReg(h0, 0b1))
                    : div(h0, x, y)));
            setRegister(rd, s32(h0, q));
            break;
        case K_Divuw:
            t x = getRegister(rs1);
            t y = getRegister(rs2);
            t q = ((reg_eqb(h0, y, coq_ZToReg(h0, 0b0)))
                ? maxUnsigned(h0)
                : divu(h0, x, y));
            setRegister(rd, s32(h0, q));
            break;
        case K_Remw:
            t x = getRegister(rs1);
            t y = getRegister(rs2);
            t r = ((reg_eqb(h0, x, minSigned(h0)) && reg_eqb(h0, y, negate(h0, coq_ZToReg(h0, 0b1))))
                ? coq_ZToReg(h0, 0b0)
                : ((reg_eqb(h0, y, coq_ZToReg(h0, 0b0)))
                    ? x
                    : rem(h0, x, y)));
            setRegister(rd, s32(h0, r));
            break;
        case K_Remuw:
            t x = getRegister(rs1);
            t y = getRegister(rs2);
            t r = ((reg_eqb(h0, y, coq_ZToReg(h0, 0b0)))
                ? x
                : remu(h0, x, y));
            setRegister(rd, s32(h0, r));
            break;
    }
}
